language: php

dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.4

env:
  global:
    - RUN_TESTS=1

matrix:
  include:
    - php: 7.2
      env: PHPCS=1 RUN_TESTS=0

    - php: 7.4
      env: CODECOVERAGE=1 RUN_TESTS=0

before_install:
  - |
      if [[ $CODECOVERAGE == 1 ]]; then
        pecl channel-update pecl.php.net
        pecl install pcov
      fi
  - phpenv config-rm xdebug.ini
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.4.deb && sudo dpkg -i --force-confnew elasticsearch-6.2.4.deb && sudo service elasticsearch restart

install:
  - composer install --prefer-dist --no-interaction

before_script:
  - sleep 7 # Work around elasticsearch startup time.

script:
  - if [[ $CODECOVERAGE == 1 ]]; then vendor/bin/phpunit --verbose --coverage-clover=clover.xml; fi
  - if [[ $RUN_TESTS == 1 ]]; then vendor/bin/phpunit --verbose; fi
  - if [[ $PHPCS == 1 ]]; then vendor/bin/phpcs -p ./src ./tests; fi

after_success:
  - |
      if [[ $CODECOVERAGE == 1 ]]; then
        wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
        chmod +x php-coveralls.phar
        ./php-coveralls.phar
      fi

notifications:
  email: false
